In [ ]:
import array
array.array('i', [2,3,4,5])

array('i', [2, 3, 4, 5])

In [ ]:
ar = array.array('i', [2,3,4,5])
ar[0]

2

In [ ]:
type(ar[0])

int

In [ ]:
type(ar[1:3])

array.array

In [ ]:
ar[1:3]

array('i', [3, 4])

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ar = np.array([[1,2,3], [4,5,6]])

In [ ]:
ar[0,0]

1

In [ ]:
ar[:,[0,1]]

array([[1, 2],
       [4, 5]])

In [ ]:
np.sum(ar)

21

In [ ]:
np.abs(ar)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import pandas as pd

In [ ]:
pd.Series([2,3,4])

0    2
1    3
2    4
dtype: int64

In [ ]:
pd.Series([2,3,4], index=['a','b','c'])

a    2
b    3
c    4
dtype: int64

In [ ]:
s = pd.Series([2,3,4], index=[1,2,3])

In [ ]:
s[1]

2

In [ ]:
s[1:3]

2    3
3    4
dtype: int64

In [ ]:
s.loc[1]

2

In [ ]:
s.loc[1:3]

1    2
2    3
3    4
dtype: int64

In [ ]:
s.iloc[0]

2

#### Type conversion

In [3]:
import pandas as pd
category = pd.Series(['Fashoin', 'Food', 'Footware', 'Electronics'])
sales = pd.Series(['2345','45764','5646', '3445'])
date = pd.Series(['12/01/2021','12/01/2021','12/01/2021','12/01/2021'])

In [4]:
category

0        Fashoin
1           Food
2       Footware
3    Electronics
dtype: object

In [5]:
category.astype('category')

0        Fashoin
1           Food
2       Footware
3    Electronics
dtype: category
Categories (4, object): ['Electronics', 'Fashoin', 'Food', 'Footware']

In [6]:
category = category.astype('category')

In [7]:
sales

0     2345
1    45764
2     5646
3     3445
dtype: object

In [8]:
sales = sales.astype('int')

In [9]:
sales

0     2345
1    45764
2     5646
3     3445
dtype: int64

In [10]:
date

0    12/01/2021
1    12/01/2021
2    12/01/2021
3    12/01/2021
dtype: object

In [11]:
date = pd.to_datetime(date, format='%d/%m/%Y')

In [12]:
date

0   2021-01-12
1   2021-01-12
2   2021-01-12
3   2021-01-12
dtype: datetime64[ns]

In [ ]:
pd.Series({'Fashion':2345, 'Food':2335, 'Footware':5456, 'Electronics':4673})

Fashion        2345
Food           2335
Footware       5456
Electronics    4673
dtype: int64

In [ ]:
ser = pd.Series({'Fashion':2345, 'Food':2335, 'Footware':5456, 'Electronics':4673})

In [ ]:
ser.index

Index(['Fashion', 'Food', 'Footware', 'Electronics'], dtype='object')

In [ ]:
ser.values

array([2345, 2335, 5456, 4673])

In [ ]:
ser['Fashion']

2345

In [ ]:
ser[0]

2345

In [ ]:
ser.loc['Fashion']

2345

In [ ]:
ser.iloc[0]

2345

### Dataframe

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'Category':category, 'Sales':sales, 'Date':date})

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [13]:
data = pd.DataFrame({'Category':category, 'Sales':sales, 'Date':date})

In [ ]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data.dtypes

Category          category
Sales                int64
Date        datetime64[ns]
dtype: object

In [ ]:
data.describe()

Sales
count      4.000000
mean   14300.000000
std    21020.847287
min     2345.000000
25%     3170.000000
50%     4545.500000
75%    15675.500000
max    45764.000000

In [ ]:
data.head()

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data.tail()

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data['Category']

0        Fashoin
1           Food
2       Footware
3    Electronics
Name: Category, dtype: category
Categories (4, object): ['Electronics', 'Fashoin', 'Food', 'Footware']

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
type(data['Sales'])

pandas.core.series.Series

In [ ]:
type(data.values)

numpy.ndarray

In [ ]:
data.values

array([['Fashoin', 2345, Timestamp('2021-01-12 00:00:00')],
       ['Food', 45764, Timestamp('2021-01-12 00:00:00')],
       ['Footware', 5646, Timestamp('2021-01-12 00:00:00')],
       ['Electronics', 3445, Timestamp('2021-01-12 00:00:00')]],
      dtype=object)

In [ ]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

## Slicing dataframes

In [ ]:
data[['Category', 'Sales']]

Category  Sales
0      Fashoin   2345
1         Food  45764
2     Footware   5646
3  Electronics   3445

In [ ]:
data.loc[:,['Category','Sales']]

Category  Sales
0      Fashoin   2345
1         Food  45764
2     Footware   5646
3  Electronics   3445

In [ ]:
data.iloc[:,[0,1]]

Category  Sales
0      Fashoin   2345
1         Food  45764
2     Footware   5646
3  Electronics   3445

In [ ]:
data.loc[0:3,:]

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data.iloc[0:3,:]

Category  Sales       Date
0   Fashoin   2345 2021-01-12
1      Food  45764 2021-01-12
2  Footware   5646 2021-01-12

In [ ]:
data.loc[0:3,['Category','Sales']]

Category  Sales
0      Fashoin   2345
1         Food  45764
2     Footware   5646
3  Electronics   3445

In [ ]:
data.iloc[0:3,0:2]

Category  Sales
0   Fashoin   2345
1      Food  45764
2  Footware   5646

In [ ]:
data.iloc[0:3,[0,1]]

Category  Sales
0   Fashoin   2345
1      Food  45764
2  Footware   5646

In [ ]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data.loc[2,'Sales']

5646

In [ ]:
data.loc[2,'Sales'] = 5764

In [ ]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5764 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data[data['Sales'] > 5000]

Category  Sales       Date
1      Food  45764 2021-01-12
2  Footware   5764 2021-01-12

In [ ]:
data.loc[data['Sales'] > 500,:]

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5764 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
data.iloc[[False, True, True, False],:]

Category  Sales       Date
1      Food  45764 2021-01-12
2  Footware   5764 2021-01-12

In [ ]:
data.iloc[data['Sales'] > 5000,:]

NotImplementedError: ignored

In [ ]:
data['Sales'] > 5000

0    False
1     True
2     True
3    False
Name: Sales, dtype: bool

In [ ]:
(data['Sales'] > 5000).values

array([False,  True,  True, False])

In [ ]:
data.iloc[[False, True, True, False],:]

Category  Sales        Date
1      Food  45764  12/01/2021
2  Footware   5646  12/01/2021

In [ ]:
data.iloc[(data['Sales'] > 5000).values,:]

Category  Sales        Date
1      Food  45764  12/01/2021
2  Footware   5646  12/01/2021

In [ ]:
data.loc[pd.Series([True,False,True,False]), 'Category']

0     Fashoin
2    Footware
Name: Category, dtype: object

In [ ]:
data.iloc[pd.Series([True,False,True,False]), 0]

NotImplementedError: ignored

In [ ]:
data.loc[data['Sales'] > 5000, 'Category']

1        Food
2    Footware
Name: Category, dtype: category
Categories (4, object): ['Electronics', 'Fashoin', 'Food', 'Footware']

In [ ]:
data['Sales'] > 5000

0    False
1     True
2     True
3    False
Name: Sales, dtype: bool

#### inserting data to dataframes

In [ ]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5764 2021-01-12
3  Electronics   3445 2021-01-12

In [ ]:
row = {'Category':'Luxury', 'Sales':3456, 'Date':'12/01/2021'}

In [ ]:
data.append(row, ignore_index=True)

Category  Sales                 Date
0      Fashoin   2345  2021-01-12 00:00:00
1         Food  45764  2021-01-12 00:00:00
2     Footware   5764  2021-01-12 00:00:00
3  Electronics   3445  2021-01-12 00:00:00
4       Luxury   3456           12/01/2021

In [ ]:
data.dtypes

Category          category
Sales                int64
Date        datetime64[ns]
dtype: object

In [ ]:
row1 = {'Category':['Luxury'], 'Sales':[3456], 'Date':['12/01/2021']}

In [ ]:
row_data1 = pd.DataFrame(row1)

In [ ]:
row2 = {'Category':'Luxury', 'Sales':3456, 'Date':'12/01/2021'}

In [ ]:
row_data2 = pd.DataFrame(row2, index=[4])

In [ ]:
row_data2

Category  Sales        Date
4   Luxury   3456  12/01/2021

In [ ]:
row_data1

Category  Sales        Date
0   Luxury   3456  12/01/2021

In [ ]:
data.append(row_data1)

Category  Sales                 Date
0      Fashoin   2345  2021-01-12 00:00:00
1         Food  45764  2021-01-12 00:00:00
2     Footware   5764  2021-01-12 00:00:00
3  Electronics   3445  2021-01-12 00:00:00
0       Luxury   3456           12/01/2021

In [ ]:
data.append(row_data2)

Category  Sales                 Date
0      Fashoin   2345  2021-01-12 00:00:00
1         Food  45764  2021-01-12 00:00:00
2     Footware   5764  2021-01-12 00:00:00
3  Electronics   3445  2021-01-12 00:00:00
4       Luxury   3456           12/01/2021

In [ ]:
# dataframes -> slice -> insert data -> UPDATE DATA 

#### Update data

In [15]:
whos

Variable   Type         Data/Info
---------------------------------
category   Series       0        Fashoin\n1      <...>oin', 'Food', 'Footware']
data       DataFrame          Category  Sales    <...>tronics   3445 2021-01-12
date       Series       0   2021-01-12\n1   2021-<...>12\ndtype: datetime64[ns]
pd         module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
sales      Series       0     2345\n1    45764\n2<...>n3     3445\ndtype: int64


In [16]:
who

category	 data	 date	 pd	 sales	 


In [17]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food  45764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [19]:
data.loc[1,'Sales']

45764

In [20]:
data.loc[1,'Sales'] = 5764

In [21]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food   5764 2021-01-12
2     Footware   5646 2021-01-12
3  Electronics   3445 2021-01-12

In [23]:
data.iloc[2,1]

5646

In [24]:
data.iloc[2,1] = 5567

In [25]:
data

Category  Sales       Date
0      Fashoin   2345 2021-01-12
1         Food   5764 2021-01-12
2     Footware   5567 2021-01-12
3  Electronics   3445 2021-01-12

In [27]:
data.loc[data['Category'] == 'Fashoin','Sales']

0    2345
Name: Sales, dtype: int64

In [28]:
data.loc[data['Category'] == 'Fashoin','Sales'] = 3456

In [29]:
data

Category  Sales       Date
0      Fashoin   3456 2021-01-12
1         Food   5764 2021-01-12
2     Footware   5567 2021-01-12
3  Electronics   3445 2021-01-12

In [30]:
data['Location'] = 'Bangalore'

In [31]:
data

Category  Sales       Date   Location
0      Fashoin   3456 2021-01-12  Bangalore
1         Food   5764 2021-01-12  Bangalore
2     Footware   5567 2021-01-12  Bangalore
3  Electronics   3445 2021-01-12  Bangalore

In [32]:
data['Distributor Location'] = ['Bangalore', 'Hyderabad', 'Mumbai', 'Chennai']

In [33]:
data

Category  Sales       Date   Location Distributor Location
0      Fashoin   3456 2021-01-12  Bangalore            Bangalore
1         Food   5764 2021-01-12  Bangalore            Hyderabad
2     Footware   5567 2021-01-12  Bangalore               Mumbai
3  Electronics   3445 2021-01-12  Bangalore              Chennai

In [34]:
data1 = data[['Category', 'Sales', 'Date', 'Distributor Location']].copy()

In [35]:
data1

Category  Sales       Date Distributor Location
0      Fashoin   3456 2021-01-12            Bangalore
1         Food   5764 2021-01-12            Hyderabad
2     Footware   5567 2021-01-12               Mumbai
3  Electronics   3445 2021-01-12              Chennai

In [38]:
data2 = data.drop(columns=['Location'])

In [37]:
data

Category  Sales       Date   Location Distributor Location
0      Fashoin   3456 2021-01-12  Bangalore            Bangalore
1         Food   5764 2021-01-12  Bangalore            Hyderabad
2     Footware   5567 2021-01-12  Bangalore               Mumbai
3  Electronics   3445 2021-01-12  Bangalore              Chennai

In [39]:
data2

Category  Sales       Date Distributor Location
0      Fashoin   3456 2021-01-12            Bangalore
1         Food   5764 2021-01-12            Hyderabad
2     Footware   5567 2021-01-12               Mumbai
3  Electronics   3445 2021-01-12              Chennai

In [42]:
data3 = data.iloc[:3,:]

In [43]:
data3

Category  Sales       Date   Location Distributor Location
0   Fashoin   3456 2021-01-12  Bangalore            Bangalore
1      Food   5764 2021-01-12  Bangalore            Hyderabad
2  Footware   5567 2021-01-12  Bangalore               Mumbai

In [45]:
del data3['Location']

In [46]:
data3

Category  Sales       Date Distributor Location
0   Fashoin   3456 2021-01-12            Bangalore
1      Food   5764 2021-01-12            Hyderabad
2  Footware   5567 2021-01-12               Mumbai

In [ ]:
# dataframes -> slicing -> insert -> update -> delete