In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [2]:
raw_data = datasets.load_iris()

In [3]:
type(raw_data)

sklearn.utils.Bunch

In [4]:
X = raw_data.data

In [5]:
raw_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
raw_data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
y = raw_data.target

In [8]:
df = pd.DataFrame(X, columns=raw_data.feature_names)

In [9]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
df['Species'] = y

In [11]:
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Species
0                  5.1               3.5  ...               0.2        0
1                  4.9               3.0  ...               0.2        0
2                  4.7               3.2  ...               0.2        0
3                  4.6               3.1  ...               0.2        0
4                  5.0               3.6  ...               0.2        0
..                 ...               ...  ...               ...      ...
145                6.7               3.0  ...               2.3        2
146                6.3               2.5  ...               1.9        2
147                6.5               3.0  ...               2.0        2
148                6.2               3.4  ...               2.3        2
149                5.9               3.0  ...               1.8        2

[150 rows x 5 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, shuffle=True)

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=500)

model.fit(X_train, y_train)

model.predict(X_test)

array([2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 2, 0, 2])

In [14]:
model.score(X_test, y_test)

0.9333333333333333

In [15]:
from sklearn.metrics import confusion_matrix
predictions = model.predict(X_test)
confusion_matrix(y_test, predictions)

array([[14,  0,  0],
       [ 0,  6,  2],
       [ 0,  0,  8]])

In [16]:
from sklearn.metrics import recall_score
recall_score(y_test, predictions, average='weighted')

0.9333333333333333

In [ ]:
from statsmodels.discrete.discrete_model import MNLogit

model = MNLogit(y, X)

fit = model.fit()

fit.summary()

         Current function value: 0.072266
         Iterations: 35


/usr/local/lib/python3.6/dist-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                          MNLogit Regression Results                          
==============================================================================
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      142
Method:                           MLE   Df Model:                            6
Date:                Mon, 15 Feb 2021   Pseudo R-squ.:                  0.9342
Time:                        04:32:25   Log-Likelihood:                -10.840
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 1.655e-63
==============================================================================
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.5753   1.01e+05   -6.5e-05      1.000   -1.98e+05    1.98e+05
x2           -10.5763   1.71e+05  -6.18e-05      1.000   -3.35e+05    3.35e+05
x3            20.2109   2.98e+05   6.78e-05      1.000   -5.85e+05    5.85e+05
x4            19.9450    6.1e+05   3.27e-05      1.000    -1.2e+06     1.2e+06
------------------------------------------------------------------------------
       y=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1           -12.9030   1.01e+05     -0.000      1.000   -1.98e+05    1.98e+05
x2           -17.1945   1.71e+05     -0.000      1.000   -3.35e+05    3.35e+05
x3            28.6447   2.98e+05    9.6e-05      1.000   -5.85e+05    5.85e+05
x4            30.2275    6.1e+05   4.95e-05      1.000    -1.2e+06     1.2e+06
==============================================================================
"""

In [ ]:
predictions = fit.predict(X_test)

In [ ]:
threshold = 0.5

predict_class = np.zeros(predictions.shape)
predict_class[predictions>threshold] = 1
predict_class

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [17]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
model.predict(X_test)


array([2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 2, 0, 2])

In [18]:
model.predict_proba(X_test)

array([[2.88064663e-105, 4.45392713e-001, 5.54607287e-001],
       [4.10804960e-224, 1.24159124e-012, 1.00000000e+000],
       [2.90027018e-046, 9.99995517e-001, 4.48287264e-006],
       [1.25622265e-108, 3.78180152e-002, 9.62181985e-001],
       [1.00000000e+000, 5.18302557e-018, 2.96672435e-027],
       [4.95724864e-148, 1.48578014e-006, 9.99998514e-001],
       [1.00000000e+000, 4.08898490e-019, 5.67898444e-028],
       [1.00000000e+000, 3.52155232e-017, 5.16365782e-027],
       [4.55897005e-244, 2.00023993e-013, 1.00000000e+000],
       [1.00000000e+000, 1.02702513e-019, 2.42294386e-029],
       [1.62692708e-049, 9.99980618e-001, 1.93822720e-005],
       [1.00000000e+000, 5.80400291e-019, 1.32350528e-027],
       [1.00000000e+000, 9.03064689e-019, 1.92692930e-027],
       [1.00000000e+000, 9.24784085e-021, 1.90434976e-029],
       [1.00000000e+000, 4.84996010e-018, 1.98612277e-027],
       [4.18620919e-088, 7.19158485e-001, 2.80841515e-001],
       [1.00000000e+000, 1.56871266e-018

In [19]:
from sklearn.metrics import confusion_matrix
predictions = model.predict(X_test)
confusion_matrix(y_test, predictions)

array([[14,  0,  0],
       [ 0,  6,  2],
       [ 0,  0,  8]])

In [20]:
model.score(X_test, y_test)

0.9333333333333333

In [23]:
from sklearn.metrics import roc_auc_score
predictions = model.predict_proba(X_test)
roc_auc_score(y_test, predictions, multi_class='ovo')

1.0

In [24]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, y_train)
model.predict(X_test)

array([2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 2, 0, 2])

In [ ]:
# decisiontree
# randomforest
# SVC
# XGBClassifier

In [25]:
# voting classifier
# decisiontree 1 
# randomforest  1
# SVC 0
# XGBClassifier 1

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.ensemble import VotingClassifier


estimators = []

logit_model = LogisticRegression(max_iter=500)
estimators.append(('Logit', logit_model))

nb_model = GaussianNB()
estimators.append(('NB', nb_model))

rf_model = RandomForestClassifier()
estimators.append(('RF', rf_model))

xgb_model = XGBClassifier()
estimators.append(('XGB', xgb_model))

voting_model = VotingClassifier(estimators, voting='soft')
voting_model.fit(X_train, y_train)
voting_model.predict(X_test)

array([2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 2, 0, 2])

In [31]:
voting_model.score(X_test, y_test)

0.9333333333333333

In [32]:
from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits=10)

from sklearn.utils import shuffle

X_s, y_s = shuffle(X,y)

cross_val = cross_val_score(voting_model, X_s, y_s, cv=kfold)

cross_val.mean()


0.96

In [34]:
from sklearn.model_selection import GridSearchCV

params = {'RF__n_estimators':[20,200], 'XGB__learning_rate':[0.5,1.0]}
search = GridSearchCV(estimator=voting_model, param_grid=params, cv=5)
search.fit(X_train, y_train)
search.predict(X_test)

array([2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 2, 0, 2])

In [35]:
search.best_params_

{'RF__n_estimators': 20, 'XGB__learning_rate': 0.5}

In [36]:
search.best_estimator_

VotingClassifier(estimators=[('Logit',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=500,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('NB',
                              GaussianNB(priors=None, var_smoothing=1e-09)),
                             ('RF',
                              RandomForestClassi...
                                            colsample_bynode=1,
                      

In [37]:
search.best_score_

0.975

In [38]:
search.score(X_test, y_test)

0.9333333333333333

In [39]:
import pickle

model_pkl_file = 'Voting_model.pkl'

file = open(model_pkl_file, 'wb')

pickle.dump(voting_model, file)

file.close()

In [40]:
model_pkl_file = 'Voting_model.pkl'
file = open(model_pkl_file, 'rb')
model = pickle.load(file)

In [41]:
model.predict(X_test)

array([2, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 2, 0, 2])