In [1]:
l = [2,3,4]

In [3]:
import array
ar = array.array('i',[1,2,3,4])

In [4]:
ar

array('i', [1, 2, 3, 4])

In [5]:
ar[0]

1

In [6]:
ar[1:2]

array('i', [2])

In [7]:
ar[1] = 3

In [8]:
ar

array('i', [1, 3, 3, 4])

In [9]:
import numpy as np
ar = np.array([1,2,3,4])

In [10]:
ar

array([1, 2, 3, 4])

In [11]:
type(ar)

numpy.ndarray

In [12]:
ar1 = np.array([[1,2,3],[4,5,6]])

In [13]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
l = [ [2,3],[4,5],[6,7],[7,8] ]

In [16]:
ar2 = np.array(l)

In [17]:
ar2.shape

(4, 2)

In [18]:
ar.shape

(4,)

In [19]:
ar1.shape

(2, 3)

In [20]:
ar.ndim

1

In [21]:
ar1.ndim

2

In [22]:
ar2.ndim

2

In [23]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8]], [[3,4,5],[7,6,5]]])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [32]:
r = np.random.rand(2,2)

In [31]:
np.random.normal((2,3))

array([1.18405297, 2.24944717])

In [33]:
r.dtype

dtype('float64')

In [34]:
# int, float, string, bool
# int8 (-128 to 127)
# int16
# int32
# int64 

# float16
# float32

In [35]:
s = np.array(['a','b','c'])

In [36]:
s

array(['a', 'b', 'c'], dtype='<U1')

In [37]:
ar = np.array([23,34,45], dtype='float16')

In [38]:
ar

array([23., 34., 45.], dtype=float16)

In [39]:
ar.dtype

dtype('float16')

In [40]:
ar = np.array([[1,2,3],[4,5,6]])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
l = [[1, 2, 3],
       [4, 5, 6]]

In [43]:
l[0]

[1, 2, 3]

In [44]:
l[0][1]

2

In [45]:
ar[0]

array([1, 2, 3])

In [46]:
ar[0][1]

2

In [47]:
ar[0,1]

2

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
ar[:,0]

array([1, 4])

In [51]:
#@title Default title text
ar[:,1]

array([2, 5])

In [52]:
ar[0,:]

array([1, 2, 3])

In [54]:
ar[:,:2]

array([[1, 2],
       [4, 5]])

In [55]:
ar[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [56]:
ar = np.array([[1,2,3],[4,5,6]])
ar1 = np.array([[4,5,6],[8,5,2]])

In [57]:
ar + ar1

array([[ 5,  7,  9],
       [12, 10,  8]])

In [58]:
ar - ar1

array([[-3, -3, -3],
       [-4,  0,  4]])

In [59]:
ar * ar1

array([[ 4, 10, 18],
       [32, 25, 12]])

In [60]:
ar / ar1

array([[0.25, 0.4 , 0.5 ],
       [0.5 , 1.  , 3.  ]])

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
sum(ar)

array([5, 7, 9])

In [63]:
np.sum(ar)

21

In [65]:
np.min(ar)

1

In [66]:
np.max(ar)

6

In [67]:
ar.dot(ar1)

ValueError: ignored

In [68]:
ar_copy = ar.copy()

In [69]:
# reshape of arrays

In [71]:
# range()
ar = np.arange(1,10)

In [72]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
ar.shape

(9,)

In [76]:
arr = ar.reshape(3,3)

In [77]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr = np.array([1,2,3])
arr1 = np.array([10,11,12])

In [81]:
np.concatenate([arr,arr1])

array([ 1,  2,  3, 10, 11, 12])

In [82]:
arr = ar.reshape(3,3)

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr1

array([10, 11, 12])

In [85]:
np.vstack([arr, arr1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
np.hstack([arr,arr1])

ValueError: ignored

In [87]:
np.array([[1,2,3],['a','b','c']])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

# Pandas

In [88]:
import pandas as pd

In [90]:
s = pd.Series([1,2,3,4])

In [91]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [92]:
s[0]

1

In [93]:
s[0:3]

0    1
1    2
2    3
dtype: int64

In [94]:
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])

In [95]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [96]:
s1['a']

1

In [97]:
s1[0]

1

In [98]:
s2 = pd.Series([1,2,3,4], index=[1,2,3,4])

In [99]:
s2

1    1
2    2
3    3
4    4
dtype: int64

In [100]:
s2[1]

1

In [101]:
s2[0:3]

1    1
2    2
3    3
dtype: int64

In [103]:
s2.loc[1]

1

In [104]:
s2.loc[1:3]

1    1
2    2
3    3
dtype: int64

In [105]:
s2.iloc[1]

2

In [106]:
s2.iloc[1:3]

2    2
3    3
dtype: int64

In [107]:
np.sum(s2)

10

In [108]:
s1 = pd.Series([1,2,3])
s2 = pd.Series([3,4,5])

In [109]:
s1 + s2

0    4
1    6
2    8
dtype: int64

In [110]:
s1 - s2

0   -2
1   -2
2   -2
dtype: int64

In [111]:
s1_copy = s1.copy()

In [112]:
s1.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [114]:
s1.dtypes

dtype('int64')

In [115]:
pd.Series([1,2,3,'a'])

0    1
1    2
2    3
3    a
dtype: object

In [116]:
s1.values

array([1, 2, 3])

In [117]:
# numpy arrays
# pandas series
# pandas dataframes